version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"

  api:
    build:
      context: .
      dockerfile: DockerfileAPI
    env_file:
      - .env
    ports:
      - "10080:10080"

