name: Trigger auto deployment for espresso-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/espresso-api-AutoDeployTrigger-dec995a6-24de-4711-aadc-409c6d4b7928.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ESPRESSOAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ESPRESSOAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ESPRESSOAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Set image tag
        run: echo "IMAGE_TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} # Pointing to the root directory of the repository
          dockerfilePath: DockerfileAPI # Corrected input key
          registryUrl: docker.io
          registryUsername: ${{ secrets.ESPRESSOAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ESPRESSOAPI_REGISTRY_PASSWORD }}
          containerAppName: espresso-api
          resourceGroup: dev-cafecit-io_group
          imageToBuild: soumitsr/espresso-api:${{ env.IMAGE_TAG }}



